name: plans_gastos
description: Aplicativo de código aberto criado para facilitar seu planejamento de futuros ganhos e gastos.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 2.3.0+19

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  intl: ^0.17.0
  flutter_masked_text: ^0.8.0
  enum_to_string: ^2.0.1
  uuid: ^3.0.5
  shared_preferences: ^2.0.9
  flutter_spinbox: ^0.7.0
  package_info_plus: ^1.3.0
  sentry_flutter: ^6.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  flutter_launcher_icons: ^0.9.2
  change_app_package_name: ^1.0.0

flutter_icons:
  android: 'launcher_icon'
  ios: true
  image_path: 'assets/images/icon_app.png'

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: WorkSans
      fonts:
        # - asset: assets/fonts/work_sans/WorkSans-Thin.ttf
        #   weight: 100
        # - asset: assets/fonts/work_sans/WorkSans-ExtraLight.ttf
        #   weight: 200
        # - asset: assets/fonts/work_sans/WorkSans-Light.ttf
        #   weight: 300
        - asset: assets/fonts/work_sans/WorkSans-Regular.ttf
          weight: 400
        # - asset: assets/fonts/work_sans/WorkSans-Medium.ttf
        #   weight: 500
        - asset: assets/fonts/work_sans/WorkSans-SemiBold.ttf
          weight: 600
        # - asset: assets/fonts/work_sans/WorkSans-Bold.ttf
        #   weight: 700
        # - asset: assets/fonts/work_sans/WorkSans-ExtraBold.ttf
        #   weight: 800
        # - asset: assets/fonts/work_sans/WorkSans-Black.ttf
        #   weight: 900
